### ISSUE TITLE
Calling Challenge.Validate() on a "dns-01" type sometimes invalidates all challenges.

### ISSUE THREAD

**Issue by zigszigsdk** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#22]
Following the change in #21 I'm now able to better pinpoint the other issue I highlid in #20 - there were two issues, of which #21 only solved one. This is about the other. 

I get the following error:
```
[40m[1m[33mwarn[39m[22m[49m: FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService[0]
      Exception occured renewing certificates: 'One or more LetsEncrypt orders were invalid. Make sure that LetsEncrypt can contact the domain you are trying to request an SSL certificate for, in order to verify it..'
FluffySpoon.AspNet.LetsEncrypt.Exceptions.OrderInvalidException: One or more LetsEncrypt orders were invalid. Make sure that LetsEncrypt can contact the domain you are trying to request an SSL certificate for, in order to verify it.
 ---> System.AggregateException: One or more errors occurred. (errortype null: null errordetails (challenge type http-01)) (urn:ietf:params:acme:error:dns: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.sub.domain.top (challenge type dns-01))
 ---> System.Exception: errortype null: null errordetails (challenge type http-01)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.Exception: urn:ietf:params:acme:error:dns: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.sub.domain.top (challenge type dns-01)<---

   --- End of inner exception stack trace ---
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order) in C:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 283
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order) in C:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 287
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.AcquireNewCertificateForDomains(String[] domains) in C:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 164
   at FluffySpoon.AspNetL.etsEncrypt.LetsEncryptRenewalService.RunOnceAsync() in C:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 141
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync() in C:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 148
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceWithErrorHandlingAsync() in C:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 107
FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService: Warning: Exception occured renewing certificates: 'One or more LetsEncrypt orders were invalid. Make sure that LetsEncrypt can contact the domain you are trying to request an SSL certificate for, in order to verify it..'

FluffySpoon.AspNet.LetsEncrypt.Exceptions.OrderInvalidException: One or more LetsEncrypt orders were invalid. Make sure that LetsEncrypt can contact the domain you are trying to request an SSL certificate for, in order to verify it.
 ---> System.AggregateException: One or more errors occurred. (errortype null: null errordetails (challenge type http-01)) (urn:ietf:params:acme:error:dns: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.sub.domain.top (challenge type dns-01))
 ---> System.Exception: errortype null: null errordetails (challenge type http-01)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.Exception: urn:ietf:params:acme:error:dns: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.sub.domain.top (challenge type dns-01)<---

   --- End of inner exception stack trace ---
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order) in C:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 283
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order) in:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 287
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.AcquireNewCertificateForDomains(String[] domains) in C:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 164
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync() in C:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 141
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync() in C:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 148
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceWithErrorHandlingAsync() in C:\git\projectName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 107
```

By looking at the acme challenge before and after the .Validate() call on the dns-01 challenge, I noticed that all three challenges change from Pending to Invalid:

```
{
  "identifier": {
    "type": "dns",
    "value": "sub.domain.top"
  },
  "status": "invalid",
  "expires": "2019-12-12T09:19:22Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/snip",
      "token": "6m6lae8SI116dSCmKDJBpxBVdlI9g8dNhHzbxvCcS6Q"
    },
    {
      "type": "dns-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:dns",
        "detail": "DNS problem: NXDOMAIN looking up TXT for _acme-challenge.sub.domain.top",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/snip",
      "token": "6m6lae8SI116dSCmKDJBpxBVdlI9g8dNhHzbxvCcS6Q"
    },
    {
      "type": "tls-alpn-01",
      "status": "invalid",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/snip",
      "token": "6m6lae8SI116dSCmKDJBpxBVdlI9g8dNhHzbxvCcS6Q"
    }
  ]
}
```
This does not happen when attempting the http-01 challenge (and there's no strategy implemented for tls-alpn-01)

By ignoring the ready-for-validation call for dns-01 like this https://github.com/zigszigsdk/FluffySpoon.AspNet.LetsEncrypt/commit/b843ba33e55d2bde091869049faa3cb745bdc07a it works, but obviously this is not a proper solution, as it removes the option for DNS challenges.

Whether it's an issue with how this project configures/uses https://github.com/fszlin/certes or if it's an issue with Certes itself, or even with LetsEncrypt, I haven't looked into.

Sadly new projects are moving into gear, so I do not expect to have more time for this, especially now that I have a hack-fix. However, perhaps someone else can use what I've found.

**Comment by ffMathy** [comment]
Thank you so much for your efforts.

Just to be sure - this is only affecting DNS renewal?

**Comment by zigszigsdk** [comment]
Technically it affects all strategies, since all of them are invalidate - but it only *happens* when trying to validate the DNS challenge. 

Furthermore, it does not appear to happen when **renewing** an existing certificate. Only when creating one from scratch (when others have already been created - don't know if that has any bearing)

And you're much welcome!

**Comment by ffMathy** [comment]
Interesting. I don't have much time lately, but if you ever get some more time to look into it, you are very welcome! I appreciate your help so far.

**Comment by zigszigsdk** [comment]
Personally I think the DNS method should just be removed - why have it if you're on a HTTP server anyway? - but I'm aware that not everyone might agree with that, and this project is quite niche as is :-)

I'll be sure to have another look if time permits it. I quite like not having to think about where the ssl cert comes from or where it goes.

**Comment by ffMathy** [comment]
You may be right. @killswtch originally added the method, which I am very happy for, since it apparently solved a problem for him.

But it may no longer be needed for him either, and you do have a good point that perhaps it's outside the scope of this library.

@killswtch what was the scenario you originally used DNS validation in this library for? Can you help describe the use case?

**Comment by killswtch** [comment]
It was a very specific use case, which more stemmed from not being able to get HTTP challenges working in a multi-application/cluster-enabled setup. I have no problem with the merge being reverted. As you say, I no longer have a use for it, nor can I test it any longer.

**Comment by ffMathy** [comment]
Thanks for your elaboration and understanding @killswtch ❤️ 

@zigszigsdk I think we should remove it in that case then!

**Comment by zigszigsdk** [comment]
It may be for the best, then.

You do need additional configuration to resolve the DNS challenge, so you need to set up a strategy for it either way. Is it correct to assume that the DNS challenge could be re-added using such a strategy configuration, should someone need it in the future?

**Comment by ffMathy** [comment]
What do you mean by additional configuration to resolve the DNS challenge? Can't we just remove everything that has something to do with DNS in this library?

**Comment by zigszigsdk** [comment]
I just don't wanna break anyone's setup if they happen to rely on the dns-01 challenge. I'm wondering how fejesable it would be for people to re-add the dns-01 challenge without modifying the source code of this project.

**Comment by ffMathy** [comment]
Ah that's what you mean. Well, it was added less than 2 weeks ago I think. I doubt there's a huge user-base counting on it.

**Comment by zigszigsdk** [comment]
I see. We should remove / revert it, then :)

**Comment by zigszigsdk** [comment]
The new release looks promising. Unfortunately I'm rate limited for valid certs on the prod-server that experienced the issue originally. I'll update once LetsEncrypt lets my server order a new cert - later this week, I presume.

**Comment by ffMathy** [comment]
Great - thanks for keeping me up to date on this!

**Comment by zigszigsdk** [comment]
Unfortunately the production server still experiences issues. I'm looking into what exactly is going on now.
Here's the console log:

```
Production
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/home/company/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService[0]
      Checking to see if in-memory LetsEncrypt certificate needs renewal.
info: FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService[0]
      Checking to see if existing LetsEncrypt certificate has been persisted and is valid.
dbug: FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService[0]
      Creating LetsEncrypt account with email support@company.dk.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://0.0.0.0:443
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://0.0.0.0:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /var/www/ReTrust-Verify/repository/201912101633
info: FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService[0]
      Ordering LetsEncrypt certificate for domains sub.domain.global.
info: FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService[0]
      Validating all pending order authorizations.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://sub.domain.global/.well-known/acme-challenge/qAtVkLSvOR3o8aStJkOFMCbeG94x3blfQbC0nZcRt7k
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 5.330900000000001ms 302
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://sub.domain.global/.well-known/acme-challenge/qAtVkLSvOR3o8aStJkOFMCbeG94x3blfQbC0nZcRt7k
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.4616ms 302
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://sub.domain.global/.well-known/acme-challenge/qAtVkLSvOR3o8aStJkOFMCbeG94x3blfQbC0nZcRt7k
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.6453ms 302
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://sub.domain.global/.well-known/acme-challenge/qAtVkLSvOR3o8aStJkOFMCbeG94x3blfQbC0nZcRt7k
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.31620000000000004ms 302
warn: FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService[0]
      Exception occured renewing certificates: 'One or more LetsEncrypt orders were invalid. Make sure that LetsEncrypt can contact the domain you are trying to request an SSL certificate for, in order to verify it..'
FluffySpoon.AspNet.LetsEncrypt.Exceptions.OrderInvalidException: One or more LetsEncrypt orders were invalid. Make sure that LetsEncrypt can contact the domain you are trying to request an SSL certificate for, in order to verify it.
 ---> System.AggregateException: One or more errors occurred. (urn:ietf:params:acme:error:connection: Fetching https://sub.domain.global/.well-known/acme-challenge/qAtVkLSvOR3o8aStJkOFMCbeG94x3blfQbC0nZcRt7k: Error getting validation data (challenge type http-01))
 ---> System.Exception: urn:ietf:params:acme:error:connection: Fetching https://sub.domain.global/.well-known/acme-challenge/qAtVkLSvOR3o8aStJkOFMCbeG94x3blfQbC0nZcRt7k: Error getting validation data (challenge type http-01)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.AcquireNewCertificateForDomains(String[] domains)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceWithErrorHandlingAsync()
```

I can't help but notice that it says that it's having trouble with http**s**://sub.domain.global/.well-known/acme-challenge/qAtVkLSvOR3o8aStJkOFMCbeG94x3blfQbC0nZcRt7k

**Comment by zigszigsdk** [comment]
It appears that the http**S** thing was just a mistake on my server, however i still do experience the same issue when attempting to create a new cert. It works fine when updating an existing one.

I added some debugging details:
```
[40m[1m[33mwarn[39m[22m[49m: FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService[0]
      Exception occured renewing certificates: 'One or more LetsEncrypt orders were invalid. Make sure that LetsEncrypt can contact the domain you are trying to request an SSL certificate for, in order to verify it..'
FluffySpoon.AspNet.LetsEncrypt.Exceptions.OrderInvalidException: One or more LetsEncrypt orders were invalid. Make sure that LetsEncrypt can contact the domain you are trying to request an SSL certificate for, in order to verify it.
 ---> System.AggregateException: One or more errors occurred. (urn:ietf:params:acme:error:unauthorized: Invalid response from http://sub.domain.top/.well-known/acme-challenge/xwdGcGdE8wOJGVbp2E00Avf7dtVqz8iYZjUSLavFltE [wan.ip.add.ress]: 404 (challenge type http-01))
 ---> System.Exception: urn:ietf:params:acme:error:unauthorized: Invalid response from http://sub.domain.top/.well-known/acme-challenge/xwdGcGdE8wOJGVbp2E00Avf7dtVqz8iYZjUSLavFltE [wan.ip.add.ress]: 404 (challenge type http-01)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order) in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 268
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order) in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 272
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.AcquireNewCertificateForDomains(String[] domains) in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 159
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync() in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 139
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync() in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 146
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceWithErrorHandlingAsync() in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 105
FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService: Warning: Exception occured renewing certificates: 'One or more LetsEncrypt orders were invalid. Make sure that LetsEncrypt can contact the domain you are trying to request an SSL certificate for, in order to verify it..'

FluffySpoon.AspNet.LetsEncrypt.Exceptions.OrderInvalidException: One or more LetsEncrypt orders were invalid. Make sure that LetsEncrypt can contact the domain you are trying to request an SSL certificate for, in order to verify it.
 ---> System.AggregateException: One or more errors occurred. (urn:ietf:params:acme:error:unauthorized: Invalid response from http://sub.domain.top/.well-known/acme-challenge/xwdGcGdE8wOJGVbp2E00Avf7dtVqz8iYZjUSLavFltE [wan.ip.add.ress]: 404 (challenge type http-01))
 ---> System.Exception: urn:ietf:params:acme:error:unauthorized: Invalid response from http://sub.domain.top/.well-known/acme-challenge/xwdGcGdE8wOJGVbp2E00Avf7dtVqz8iYZjUSLavFltE [wan.ip.add.ress]: 404 (challenge type http-01)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order) in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 268
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order) in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 272
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.AcquireNewCertificateForDomains(String[] domains) in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 159
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync() in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 139
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync() in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 146
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceWithErrorHandlingAsync() in C:\git\ApplicationName\FluffySpoon.AspNet.LetsEncrypt\LetsEncryptRenewalService.cs:line 105
```

This time it's with the source code from 1.133

**Comment by zigszigsdk** [comment]
Reverting to source code of 1.131 worked.
So did using the nuget package of 1.131 - both through offroad debugging and my normal build pipeline.

With the code from 1.133 it the http-01 challenge failed when the following line is called:
```
challenges = await Task.WhenAll(challengeContexts.Select(x => x.Resource()));
```

In other words, our fix worked as it should -- but either 1.132 or 1.133 broke it again.

**Comment by ffMathy** [comment]
@dv00d00 got any ideas? It happened after the response changes you made.

**Comment by zigszigsdk** [comment]
No comment, I guess. I'll check if I can reproduce the issue in a newer version and check back in.

**Comment by zigszigsdk** [comment]
It works as expected in the latest version, so this was resolved in one of the releases between (inc.) 1.134 1.139

**Comment by dv00d00** [comment]
Sorry for the late reply looks like this was related to https://github.com/ffMathy/FluffySpoon.AspNet.LetsEncrypt/pull/29

I will try to submit a full flow integration test with mocked letsencrypt apis to prevent it from happening in future

**Comment by zigszigsdk** [comment]
Thanks for your hard work :)
