### ISSUE TITLE
adding domain names fails

### ISSUE THREAD

**Issue by namtab00** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#70]
Hi.

I had initially setup everything with one domain name, running correctly.
Renewal is setup 30 days / 7 days

I've added two domain names. This fails in the validation phase with:

```
WARN  2020-05-14 19:37:20,592 [7    ] ncrypt.Certes.ILetsEncryptRenewalService - Exception occured renewing certificates: 'Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/finalize/84388460/3364408420'.
urn:ietf:params:acme:error:orderNotReady: Order's status ("pending") is not acceptable for finalization.'
Certes.AcmeRequestException: Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/finalize/84388460/3364408420'.
urn:ietf:params:acme:error:orderNotReady: Order's status ("pending") is not acceptable for finalization
   at Certes.Acme.IAcmeHttpClientExtensions.Post[T](IAcmeHttpClient client, Uri uri, Object payload, Boolean ensureSuccessStatusCode)
   at Certes.Acme.OrderContext.Finalize(Byte[] csr)
   at Certes.IOrderContextExtensions.Finalize(IOrderContext context, CsrInfo csr, IKey key)
   at Certes.IOrderContextExtensions.Generate(IOrderContext context, CsrInfo csr, IKey key)
   at FluffySpoon.AspNet.LetsEncrypt.Certes.LetsEncryptClient.AcquireCertificateBytesFromOrderAsync(IOrderContext order)
   at FluffySpoon.AspNet.LetsEncrypt.Certes.LetsEncryptClient.FinalizeOrder(PlacedOrder placedOrder)
   at FluffySpoon.AspNet.LetsEncrypt.Certificates.CertificateProvider.RequestNewLetsEncryptCertificate()
   at FluffySpoon.AspNet.LetsEncrypt.Certificates.CertificateProvider.RequestNewLetsEncryptCertificate()
   at FluffySpoon.AspNet.LetsEncrypt.Certificates.CertificateProvider.RenewCertificateIfNeeded(X509Certificate2 current)
   at FluffySpoon.AspNet.LetsEncrypt.Certes.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.LetsEncrypt.Certes.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.LetsEncrypt.Certes.LetsEncryptRenewalService.RunOnceWithErrorHandlingAsync()
```

I've tried with and without wiping the saves **_Account** and **_Site** files.

What is the correct way to add names to an already configured certificate ?

**Comment by namtab00** [comment]
Might [this ](https://community.letsencrypt.org/t/error-when-finalizing-order/104649) be relevant ?

**Comment by namtab00** [comment]
I've also tried varying all configured values (email, csr info, certificate prefix), but I'm getting the same error...

Here is my mapped json config (censored values):

 ```
"LetsEncrypt": {
    "Enabled": true,
    "CertFilesRelativePath": "App_Data\\LetsEncrypt",
    "CertFilesPrefix": "multitenant_cert_staging",
    "Email": "some email", //LetsEncrypt will send an e-mail here when the certificate is about to expire
    "Domains": [ "domain 1", "domain 2" ],
    "UseStaging": true, //switch to true to generate test certs ( these are invalid)
    "TimeUntilExpiryBeforeRenewal": "30", //renew automatically 30 days before expiry
    "TimeAfterIssueDateBeforeRenewal": "7", //renew automatically 7 days after the last certificate was issued
    "CertificateSigningRequest": {
      "CountryName": "country",
      "Locality": "country code",
      "Organization": "org",
      "OrganizationUnit": "org unit",
      "State": "us state"
    }
  },
```

**Comment by willdean** [comment]
A couple of things:

* It is trying to generate a completely new certificate - there isn't a problem in that regard.
* There isn't a general problem generating certificates with multiple domains, I've just done that here as a test.

There may be more trace at the most verbose level (the level beyond 'Debug') - I'm not quite sure how you're capturing the log, but it seems to be doubling-up a lot of lines?

When you ask for multiple domains in a certificate, the LE systems will send challenges for each of the domains - is your app definitely able to serve requests for both those domains?
