### ISSUE TITLE
Null pointer during validating all pending order authorizations

### ISSUE THREAD

**Issue by ShawnRG** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#8]
Hi i'm getting this null pointer exception:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.<>c.<ValidateOrderAsync>b__25_1(IChallengeContext x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(IOrderContext order)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.AcquireNewCertificateForDomains(String[] domains)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.<StartAsync>b__16_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I'm currently running the app on the latest version of .net core 2.1, but I couldn't upgrade your package to the latest version (1.118.0). I'm now using version 1.109.0.

Could this be the issue?

Thanks in advance

**Comment by ffMathy** [comment]
Why weren't you able to upgrade?

**Comment by ShawnRG** [comment]
This is the nuget log:
```
NU1107: Version conflict detected for Microsoft.AspNetCore.Connections.Abstractions. Install/reference Microsoft.AspNetCore.Connections.Abstractions 2.2.0 directly to project API to resolve this issue. 
 API -> FluffySpoon.AspNet.LetsEncrypt 1.118.0 -> Microsoft.AspNetCore.Connections.Abstractions (>= 2.2.0) 
 API -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.AspNetCore.Connections.Abstractions (>= 2.1.1 && < 2.2.0).
```

**Comment by ffMathy** [comment]
Yes, it does unfortunately. We keep our packages up to date - you should consider doing the same.

I think updating to the latest version should resolve the issue.
